print("start routes")
from src.routes.admin_auth import router as admin_auth_router; print("admin_auth")
from src.routes.client_auth import router as client_auth_router; print("client_auth")
from src.routes.content import router as content_router; print("content")
from src.routes.blog import router as blog_router; print("blog")
from src.routes.demo_requests import router as demo_router; print("demo")
from src.routes.clients import router as clients_router; print("clients")
from src.routes.client_dashboard import router as client_dashboard_router; print("client_dashboard")
from src.routes.uploads import router as uploads_router; print("uploads")
from src.routes.password_reset import router as password_reset_router; print("password")
from src.routes.notifications import router as notifications_router; print("notifications")
from src.routes.security import router as security_router; print("security")
from src.routes.architecture import router as architecture_router; print("architecture")
from src.routes.seo import router as seo_router; print("seo")
print("all routes ok")
