print("start")
import boto3; print("boto3 ok")
from src.config import Config; print("config ok")
import langchain_classic; print("lc ok")
from langchain_classic.agents import AgentExecutor; print("executor ok")
from langchain_aws import ChatBedrock; print("bedrock ok")
from langchain.prompts import ChatPromptTemplate; print("template ok")
from langchain.tools import tool; print("tool ok")
print("all OK")
