print("start main")
from fastapi import FastAPI, HTTPException; print("1")
from fastapi.middleware.cors import CORSMiddleware; print("2")
from pydantic import BaseModel; print("3")
from src.agents.red_agent import RedAgent; print("4")
from src.agents.blue_agent import BlueAgent; print("5")
import boto3; print("6")
from datetime import datetime; print("7")
from src.config import Config; print("8")
import uuid; print("9")
import os; print("10")
from dotenv import load_dotenv; print("11")
load_dotenv(); print("12")
from src.core.orchestrator import AgentOrchestrator; print("13")
from src.core.database import Database; print("14")
from src.core.n8n_client import N8NClient; print("15")
from src.core.llm_client import LLMClient; print("16")
from src.core.memory import CampaignMemoryManager; print("17")
from src.core.hooks import SecurityHookProvider, AttackDefenseFeedbackHook; print("18")
from src.utils.logger import setup_logger; print("19")
